#!/bin/sh
set -e

if [ $# -lt 1 ]; then
  echo "$0 x86|x86_64|armeabi-v7a|arm64-v8a [.../]configure [args...]" 1>&2
  exit 1
fi
if [ "$ANDROID_NDK_ROOT" = "" ]; then
  echo "FATAL: You must export ANDROID_NDK_ROOT" 1>&2
  exit 1
fi

architecture=$1
shift

if [ "$architecture" = "x86" ]; then
  tool_prefix=i686-linux-android
  compiler_prefix=${tool_prefix}16
  configureflags="--host=$tool_prefix"

elif [ "$architecture" = "x86_64" ]; then
  tool_prefix=x86_64-linux-android
  compiler_prefix=${tool_prefix}21
  configureflags="--host=$tool_prefix"

elif [ "$architecture" = "armeabi-v7a" ]; then
  # There is some inconsistency in tool names
  tool_prefix=arm-linux-androideabi
  compiler_prefix=armv7a-linux-androideabi16
  extraflags="-mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb"
  configureflags="--host=$compiler_prefix"

elif [ "$architecture" = "arm64-v8a" ]; then
  tool_prefix=aarch64-linux-android
  compiler_prefix=${tool_prefix}21
  configureflags="--host=$tool_prefix"

else
  echo "$0: unsupported architecture: $architecture" 1>&2
  exit 1
fi

sysname="`uname -s|tr [A-Z] [a-z]`-`uname -m`"

set -x
export AR="$tool_prefix-ar"
export AS="$tool_prefix-as"
export CC="$compiler_prefix-clang"
export CFLAGS="-O2 -fPIC $extraflags"
export CPP="$compiler_prefix-clang -E"
export CXX="$compiler_prefix-clang++"
export CXXFLAGS="-O2 -fPIC $extraflags"
export LD="$tool_prefix-ld"
export NM="$tool_prefix-nm"
export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$sysname/bin/:$PATH"
export RANLIB="$tool_prefix-ranlib"
export STRIP="$tool_prefix-strip"

$@ $configureflags
