#!/bin/sh
set -e

if [ $# -lt 1 ]; then
  echo "$0 i386|x86_64|armv7s|arm64 [.../]configure [args...]" 1>&2
  exit 1
fi

architecture=$1
shift

minversion="9.0"

if [ "$architecture" = "armv7s" -o "$architecture" = "arm64" ]; then
  configureflags="--host=arm-apple-darwin --target=arm-apple-darwin"
  minversion_flag="-miphoneos-version-min=$minversion"
  if [ "$architecture" = "armv7s" ]; then
    # See measurement-kit/measurement-kit#1404
    # TODO(bassosimone): This should be in `./measurement-kit`
    extra_cppflags="-DMK_NO_THREAD_LOCAL"
  fi
  platform=iphoneos

elif [ "$architecture" = "i386" ]; then
  configureflags="--host=i386-apple-darwin --target=i386-apple-darwin"
  minversion_flag="-mios-simulator-version-min=$minversion"
  # See measurement-kit/measurement-kit#1404
  # TODO(bassosimone): This should be in `./measurement-kit`
  extra_cppflags="-DMK_NO_THREAD_LOCAL"
  platform=iphonesimulator

elif [ "$architecture" = "x86_64" ]; then
  configureflags="--host=x86_64-apple-darwin --target=x86_64-apple-darwin"
  minversion_flag="-mios-simulator-version-min=$minversion"
  platform=iphonesimulator

else
  echo "$0: unsupported architecture: $architecture" 1>&2
  exit 1
fi

isysroot="-isysroot `xcrun -sdk $platform --show-sdk-path`"

export CC="`xcrun -find -sdk $platform cc`"
export CXX="`xcrun -find -sdk $platform g++`"
export CPPFLAGS="-arch $architecture $isysroot $extra_cppflags $CPPFLAGS"
export CFLAGS="-O2 -arch $architecture $isysroot $minversion_flag $CFLAGS"
export CXXFLAGS="-O2 -arch $architecture $isysroot $minversion $CXXFLAGS"
export LDFLAGS="-arch $architecture $minversion $isysroot $LDFLAGS"

$@ $configureflags
